version: "3.9"
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    hostname: homeassistant
    network_mode: host
    depends_on:
      - mosquitto
    environment:
      - DISABLE_JEMALLOC=true
    volumes:
      - ./volumes/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
  mosquitto:
    image: eclipse-mosquitto:latest    
    restart: unless-stopped
    hostname: mosquitto
    network_mode: host
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    hostname: zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - ./volumes/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Kiev
    devices:
      - /dev/ttyUSB6:/dev/ttyACM0
