version: "3.9"
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2022.4.6
    restart: unless-stopped
    privileged: true
    hostname: homeassistant
    network_mode: host
    depends_on:
      - mosquitto
    environment:
      - DISABLE_JEMALLOC=true
    volumes:
      - ./volumes/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
  mosquitto:
    image: eclipse-mosquitto:2.0.14    
    restart: unless-stopped
    hostname: mosquitto
    network_mode: host
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.25.0
    restart: unless-stopped
    hostname: zigbee2mqtt
    network_mode: host
    depends_on:
      - mosquitto
    volumes:
      - type: bind
        source: ./volumes/zigbee2mqtt/data/configuration.yaml
        target: /app/configuration.yaml
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Kiev
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
