version: "3.9"
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    hostname: homeassistant
    network_mode: host
    depends_on:
      - mosquitto
    environment:
      - DISABLE_JEMALLOC=true
    volumes:
      - /volumes/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
  mosquitto:
    image: eclipse-mosquitto:latest    
    restart: always
    hostname: mosquitto
    network_mode: host
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
