version: "3.9"
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    hostname: homeassistant
    network_mode: host
    depends_on:
      - mosquitto
    environment:
      - DISABLE_JEMALLOC=true
    volumes:
      - ./volumes/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
  mosquitto:
    image: eclipse-mosquitto:latest    
    restart: unless-stopped
    hostname: mosquitto
    network_mode: host
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    hostname: zigbee2mqtt
    network_mode: host
    depends_on:
      - mosquitto
    volumes:
      - type: bind
        source: ./volumes/zigbee2mqtt/data/configuration.yaml
        target: /app/data/configuration.yaml
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Kiev
    devices:
      - /dev/ttyUSB6:/dev/ttyACM0
