kitchen_automation:
  automation:
    - id: kitchen_automation_motion_on_me_home
      alias: Kitchen - Automation - Motion On - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_02_01_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 4
        - condition: time
          after: "16:00:00"
          before: "22:00:00"
        - condition: state
          entity_id: light.kitchen
          state: "off"
      action:
        - service: light.turn_on
          target:
            entity_id: light.kitchen

    - id: kitchen_automation_motion_off_me_home
      alias: Kitchen - Automation - Motion Off - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_02_01_occupancy
          from: "on"
          to: "off"
          for:
            minutes: 10
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 4
        - condition: time
          after: "16:00:00"
          before: "22:00:00"
        - condition: state
          entity_id: light.kitchen
          state: "on"
      action:
        - service: light.turn_off
          target:
            entity_id: light.kitchen

    - id: kitchen_automation_button_single
      alias: Kitchen - Automation - Button - Single
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_02_01_action
          to: "single"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.toggle
          target:
            entity_id: light.kitchen

    - id: kitchen_automation_button_double
      alias: Kitchen - Automation - Button - Double
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_02_01_action
          to: "double"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_off
          target:
            entity_id:
              - light.hallway
              - light.kids_bedroom
              - light.parents_bedroom

    - id: kitchen_automation_button_long
      alias: Kitchen - Automation - Button - Long
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_02_01_action
          to: "long"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_off
          target:
            entity_id:
              - light.hallway
              - light.kitchen
              - light.kids_bedroom
              - light.parents_bedroom
