kitchen_automation:
  automation:
    - id: kitchen_automation_motion_on_me_home
      alias: Kitchen - Automation - Motion On - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_02_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_on
          target:
            entity_id: light.kitchen

    - id: kitchen_automation_motion_off_me_home
      alias: Kitchen - Automation - Motion Off - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_02_occupancy
          from: "on"
          to: "off"
          for:
            minutes: 4
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: state
          entity_id: light.kitchen
          state: "on"
      action:
        - service: light.turn_off
          target:
            entity_id: light.kitchen

    - id: kitchen_automation_switch_single_press
      alias: Kitchen - Automation - Switch - Single Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_02_action
          to: "single"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.toggle
          target:
            entity_id: light.kitchen

    - id: kitchen_automation_switch_long_press
      alias: Kitchen - Automation - Switch - Long Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_02_action
          to: "long"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: script.turn_on
          target:
              entity_id: script.all_lights_off
