kitchen_automation:
  automation:
    - id: kitchen_automation_motion_me_home
      alias: Kitchen - Automation - Motion - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.0x00124b00251c45aa_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_on
          target:
            entity_id: light.kitchen

    - id: kitchen_automation_motion_me_not_home
      alias: Kitchen - Automation - Motion - Me Not Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.0x00124b00251c45aa_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "not_home"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Security: Motion detected in the kitchen."

    - id: kitchen_automation_switch_single_press
      alias: Kitchen - Automation - Switch - Single Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.sonoff_switch_02_action
          to: "single"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.toggle
          target:
            entity_id: light.kitchen

    - id: kitchen_automation_switch_long_press
      alias: Kitchen - Automation - Switch - Long Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.sonoff_switch_02_action
          to: "long"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: script.turn_on
          target:
              entity_id: script.all_lights_off
        - service: notify.telegram_user_oleksandr
          data:
            message: "Automation: All lights are off."
