kitchen_customize:
    homeassistant:
      customize:

        sensor.snzb_01_02_01_action:
          friendly_name: Kitchen, Button
        sensor.snzb_01_02_01_battery:
          friendly_name: Kitchen, Button

        sensor.snzb_02_02_01_temperature:
          friendly_name: Kitchen, Climate Sensor
        sensor.snzb_02_02_01_humidity:
          friendly_name: Kitchen, Climate Sensor
        sensor.snzb_02_02_01_battery:
          friendly_name: Kitchen, Climate Sensor

        binary_sensor.snzb_03_02_01_occupancy:
          friendly_name: Kitchen, Motion Sensor
        sensor.snzb_03_02_01_battery:
          friendly_name: Kitchen, Motion Sensor

        binary_sensor.snzb_04_02_01_contact:
          friendly_name: Kitchen, Window Sensor
        sensor.snzb_04_02_01_battery:
          friendly_name: Kitchen, Window Sensor
