kitchen_mqtt:
  mqtt:
    light:
      - name: "Kitchen Light"
        object_id: kitchen
        state_topic: "uswitch/0x0001/channel/0x02/getvalue"
        command_topic: "uswitch/0x0001/channel/0x02/setvalue"
        retain: true
