kitchen_sensor:
  sensor:
    - platform: history_stats
      name: Kitchen Sensor Light On Duration Today
      entity_id: light.kitchen
      state: "on"
      type: time
      start: "{{ now().replace(hour=0, minute=0, second=0) }}"
      end: "{{ now() }}"
    - platform: history_stats
      name: Kitchen Sensor Window Close Duration Last Two Hourse
      entity_id: binary_sensor.snzb_04_02_contact
      state: "off"
      type: time
      end: "{{ now() }}"
      duration:
        hours: 2
