kitchen_sensor:
  sensor:
    - platform: history_stats
      name: kitchen_sensor_light_on_duration_daily
      entity_id: light.kitchen
      state: "on"
      type: time
      start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
      end: "{{ now() }}"
    - platform: history_stats
      name: kitchen_sensor_light_on_duration_monthly
      entity_id: light.kitchen
      state: "on"
      type: time
      start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"
      end: "{{ now() }}"
    - platform: template
      sensors:
        kitchen_sensor_energy_light_daily:
          friendly_name: "Kitchen Sensor Energy Light Daily: "
          value_template: "{{ states('sensor.kitchen_sensor_light_on_duration_daily') | float * 4 * 8 * 0.001 }}"
          unit_of_measurement: kWh
          icon_template: mdi:counter
        kitchen_sensor_energy_light_monthly:
          friendly_name: "Kitchen Sensor Energy Light Monthly: "
          value_template: "{{ states('sensor.kitchen_sensor_light_on_duration_monthly') | float * 4 * 8 * 0.001 }}"
          unit_of_measurement: kWh
          icon_template: mdi:counter
        kitchen_sensor_energy_socket_daily:
          friendly_name: "Kitchen Sensor Energy Socket Daily: "
          value_template: "{{ 0 }}"
          unit_of_measurement: kWh
          icon_template: mdi:counter
        kitchen_sensor_energy_socket_monthly:
          friendly_name: "Kitchen Sensor Energy Socket Monthly: "
          value_template: "{{ 0 }}"
          unit_of_measurement: kWh
          icon_template: mdi:counter
