parents_bedroom_automation_climate:
  automation:
    - id: parents_bedroom_automation_climate_window_close_long
      alias: Parents Bedroom - Automation - Climate - Window Close - Long
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_04_04_contact
          to: "off"
          for:
            hours: 2
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "_Climate_: It's time to open the window in the parents bedroom for ventilation."
