parents_bedroom_automation:
  automation:
    - id: parents_bedroom_automation_light_on_morning_me_home
      alias: Parents Bedroom - Automation - Light On - Morning - Me Home
      initial_state: true
      trigger:
        - platform: time
          at: "07:00:00"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: state
          entity_id: light.parents_bedroom
          state: "off"
      action:
        - service: light.turn_on
          target:
            entity_id: light.parents_bedroom

    - id: parents_bedroom_automation_motion_on_me_home
      alias: Parents Bedroom - Automation - Motion On - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_04_01_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 4
        - condition: time
          after: "16:00:00"
          before: "23:00:00"
        - condition: state
          entity_id: light.parents_bedroom
          state: "off"
      action:
        - service: light.turn_on
          target:
            entity_id: light.parents_bedroom

    - id: parents_bedroom_automation_motion_off_me_home
      alias: Parents Bedroom - Automation - Motion Off - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_04_01_occupancy
          from: "on"
          to: "off"
          for:
            minutes: 20
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 4
        - condition: time
          after: "16:00:00"
          before: "23:00:00"
        - condition: state
          entity_id: light.parents_bedroom
          state: "on"
      action:
        - service: light.turn_off
          target:
            entity_id: light.parents_bedroom

    - id: parents_bedroom_automation_button_single
      alias: Parents Bedroom - Automation - Button - Single
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_04_01_action
          to: "single"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.toggle
          target:
            entity_id: light.parents_bedroom

    - id: parents_bedroom_automation_button_double
      alias: Parents Bedroom - Automation - Button - Double
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_04_01_action
          to: "double"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_off
          target:
            entity_id:
              - light.hallway
              - light.kitchen
              - light.kids_bedroom

    - id: parents_bedroom_automation_button_long
      alias: Parents Bedroom - Automation - Button - Long
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_04_01_action
          to: "long"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_off
          target:
            entity_id:
              - light.hallway
              - light.kitchen
              - light.kids_bedroom
              - light.parents_bedroom
