parents_bedroom_automation:
  automation:
    - id: parents_bedroom_automation_window_close_long
      alias: Parents Bedroom - Automation - Window Close - Long
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_04_04_contact
          to: "off"
          for:
            hours: 2
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Climate: It's time to open the window in the parents bedroom for ventilation."

    - id: parents_bedroom_automation_motion_on_me_home
      alias: Parents Bedroom - Automation - Motion On - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_04_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_on
          target:
            entity_id: light.parents_bedroom

    - id: parents_bedroom_automation_motion_on_me_away
      alias: Parents Bedroom - Automation - Motion On - Me Away
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_04_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "not_home"
      action:
        - service: light.turn_on
          target:
            entity_id: light.parents_bedroom
        - service: notify.telegram_user_oleksandr
          data:
            message: "Security: Motion detected in the parents bedroom."

    - id: parents_bedroom_automation_motion_off_me_home
      alias: Parents Bedroom - Automation - Motion Off - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_04_occupancy
          from: "on"
          to: "off"
          for:
            minutes: 4
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: state
          entity_id: light.parents_bedroom
          state: "on"
      action:
        - service: light.turn_off
          target:
            entity_id: light.parents_bedroom

    - id: parents_bedroom_automation_switch_single_press
      alias: Parents Bedroom - Automation - Switch - Single Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_04_action
          to: "single"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.toggle
          target:
            entity_id: light.parents_bedroom

    - id: parents_bedroom_automation_switch_long_press
      alias: Parents Bedroom - Automation - Switch - Long Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_04_action
          to: "long"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: script.turn_on
          target:
              entity_id: script.all_lights_off
