parents_bedroom_sensor:
  sensor:
    - platform: history_stats
      name: parents_bedroom_sensor_light_on_duration_daily
      entity_id: light.parents_bedroom
      state: "on"
      type: time
      start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
      end: "{{ now() }}"
    - platform: history_stats
      name: parents_bedroom_sensor_light_on_duration_monthly
      entity_id: light.parents_bedroom
      state: "on"
      type: time
      start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"
      end: "{{ now() }}"
    - platform: template
      sensors:
        parents_bedroom_sensor_energy_light_daily:
          friendly_name: "Parents Bedroom Sensor Energy Light Daily: "
          value_template: "{{ states('sensor.parents_bedroom_sensor_light_on_duration_daily') | float * 8 * 8 }}"
          unit_of_measurement: W
          icon_template: mdi:counter
        parents_bedroom_sensor_energy_light_monthly:
          friendly_name: "Parents Bedroom Sensor Energy Light Monthly: "
          value_template: "{{ states('sensor.parents_bedroom_sensor_light_on_duration_monthly') | float * 8 * 8 }}"
          unit_of_measurement: W
          icon_template: mdi:counter
        parents_bedroom_sensor_energy_socket_daily:
          friendly_name: "Parents Bedroom Sensor Energy Socket Daily: "
          value_template: "{{ 0 }}"
          unit_of_measurement: W
          icon_template: mdi:counter
        parents_bedroom_sensor_energy_socket_monthly:
          friendly_name: "Parents Bedroom Sensor Energy Socket Monthly: "
          value_template: "{{ 0 }}"
          unit_of_measurement: W
          icon_template: mdi:counter
