balcony_mqtt:
  light:
    - platform: mqtt
      name: "Balcony Light"
      object_id: balcony
      state_topic: "udimmer/channel5/getstate"
      command_topic: "udimmer/channel5/setstate"
      brightness_state_topic: "udimmer/channel5/getbrightness"
      brightness_command_topic: "udimmer/channel5/setbrightness"
      brightness_scale: 100
      retain: true
