system_energy:
  utility_meter:
    daily_total_energy:
      source: sensor.all_sensor_energy_total_daily
      name: Daily Total Energy
      cycle: daily
      tariffs:
        - peak
        - offpeak
    monthly_total_energy:
      source: sensor.all_sensor_energy_total_monthly
      name: Monthly Total Energy
      cycle: monthly
      tariffs:
        - peak
        - offpeak
    daily_light_energy:
      source: sensor.all_sensor_energy_light_daily
      name: Daily Light Energy
      cycle: daily
      tariffs:
        - peak
        - offpeak
    monthly_light_energy:
      source: sensor.all_sensor_energy_light_monthly
      name: Monthly Light Energy
      cycle: monthly
      tariffs:
        - peak
        - offpeak
    daily_socket_energy:
      source: sensor.all_sensor_energy_socket_daily
      name: Daily Socket Energy
      cycle: daily
      tariffs:
        - peak
        - offpeak
    monthly_socket_energy:
      source: sensor.all_sensor_energy_socket_monthly
      name: Monthly Socket Energy
      cycle: monthly
      tariffs:
        - peak
        - offpeak
    monthly_gas:
        source: sensor.gas_consumption
        name: Monthly Gas
        cycle: monthly
    monthly_water:
        source: sensor.water_consumption
        name: Monthly Water
        cycle: monthly

  automation:
    - id: system_automation_energy_tariff_switch
      alias: System - Automation - Energy - Tariff Switch
      initial_state: true
      trigger:
        - platform: time
          at: "07:00:00"
          variables:
            tariff: "peak"
        - platform: time
          at: "23:00:00"
          variables:
            tariff: "offpeak"
      action:
        - service: select.select_option
          target:
            entity_id:
              - select.daily_total_energy
              - select.daily_light_energy
              - select.daily_socket_energy
              - select.monthly_total_energy
              - select.monthly_light_energy
              - select.monthly_socket_energy
          data:
            option: "{{ tariff }}"
