hallway_automation:
  automation:
  - id: Hallway Lighting on when dark outside
    alias: hallway_light_turn_on_when_dark_outside
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        # Can be a positive or negative number
        below: -4.0
    action:
      - service: light.turn_on
        target:
          entity_id: light.hallway

    - id: hallway_automation_motion
      alias: Hallway - Automation - Motion
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.0x00124b00251c48d1_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "not_home"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Security: Motion detected in the hallway."
