hallway_automation:
  automation:
    - id: Hallway Lighting on when dark outside
      alias: hallway_light_turn_on_when_dark_outside
      trigger:
        - platform: numeric_state
          entity_id: sun.sun
          attribute: elevation
          # Can be a positive or negative number
          below: -4.0
      action:
        - service: light.turn_on
          target:
            entity_id: light.hallway

    - id: hallway_automation_door_open_long
      alias: Hallway - Automation - Door Open - Long
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_04_01_contact
          not_from:
            - "unknown"
            - "unavailable"
          to: "on"
          for:
            seconds: 5
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Security: The door continues to be open for a long time."

    - id: hallway_automation_door_open_me_home
      alias: Hallway - Automation - Door Open - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_04_01_contact
          not_from:
            - "unknown"
            - "unavailable"
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: state
          entity_id: light.hallway
          state: "off"
      action:
        - service: light.turn_on
          target:
            entity_id: light.hallway

    - id: hallway_automation_door_open_me_away
      alias: Hallway - Automation - Door Open - Me Away
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_04_01_contact
          not_from:
            - "unknown"
            - "unavailable"
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "not_home"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Security: The door is open."

    - id: hallway_automation_door_close_me_away
      alias: Hallway - Automation - Door Close - Me Away
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_04_01_contact
          from: "on"
          to: "off"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "not_home"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Security: The door is closed."

    - id: hallway_automation_motion_on_me_home
      alias: Hallway - Automation - Motion On - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.0x00124b00251c48d1_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_on
          target:
            entity_id: light.hallway

    - id: hallway_automation_motion_on_me_away
      alias: Hallway - Automation - Motion On - Me Away
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.0x00124b00251c48d1_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "not_home"
      action:
        - service: light.turn_on
          target:
            entity_id: light.hallway
        - service: notify.telegram_user_oleksandr
          data:
            message: "Security: Motion detected in the hallway."

    - id: hallway_automation_motion_off_me_home
      alias: Hallway - Automation - Motion Off - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.0x00124b00251c48d1_occupancy
          from: "on"
          to: "off"
          for:
            minutes: 4
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_off
          target:
            entity_id: light.hallway

    - id: hallway_automation_switch_single_press
      alias: Hallway - Automation - Switch - Single Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.0x00124b002266532b_action
          to: "single"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.toggle
          target:
            entity_id: light.hallway

    - id: hallway_automation_switch_long_press
      alias: Hallway - Automation - Switch - Long Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.0x00124b002266532b_action
          to: "long"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: script.turn_on
          target:
              entity_id: script.all_lights_off
        - service: notify.telegram_user_oleksandr
          data:
            message: "Automation: All lights are off."
