hallway_automation:
  automation:
    - id: Hallway Lighting on when dark outside
      alias: hallway_light_turn_on_when_dark_outside
      trigger:
        - platform: numeric_state
          entity_id: sun.sun
          attribute: elevation
          # Can be a positive or negative number
          below: -4.0
      action:
        - service: light.turn_on
          target:
            entity_id: light.hallway

    - id: hallway_automation_door_open_me_home
      alias: Hallway - Automation - Door Open - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_04_01_contact
          not_from:
            - "unknown"
            - "unavailable"
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: state
          entity_id: light.hallway
          state: "off"
      action:
        - service: light.turn_on
          target:
            entity_id: light.hallway

    - id: hallway_automation_motion_on_me_home
      alias: Hallway - Automation - Motion On - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_01_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 8
      action:
        - service: light.turn_on
          target:
            entity_id: light.hallway

    - id: hallway_automation_motion_off_me_home
      alias: Hallway - Automation - Motion Off - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_01_occupancy
          from: "on"
          to: "off"
          for:
            minutes: 4
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 8
        - condition: state
          entity_id: light.hallway
          state: "on"
      action:
        - service: light.turn_off
          target:
            entity_id: light.hallway

    - id: hallway_automation_switch_single
      alias: Hallway - Automation - Switch - Single
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_01_action
          to: "single"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.toggle
          target:
            entity_id: light.hallway

    - id: hallway_automation_switch_double
      alias: Hallway - Automation - Switch - Double
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_01_action
          to: "double"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_off
          target:
            entity_id:
              - light.kitchen
              - light.kids_bedroom
              - light.parents_bedroom

    - id: hallway_automation_switch_long
      alias: Hallway - Automation - Switch - Long
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_01_action
          to: "long"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_off
          target:
            entity_id:
              - light.hallway
              - light.kitchen
              - light.kids_bedroom
              - light.parents_bedroom
