hallway_mqtt:
  sensor:
    - platform: mqtt
      name: "Mains Frequency"
      object_id: frequency
      state_topic: "udimmer/system/getfrequency"
      unit_of_measurement: "Hz"
      device_class: frequency
      state_class: measurement
  light:
    - platform: mqtt
      name: "Hallway Light"
      object_id: hallway
      state_topic: "udimmer/channel4/getstate"
      command_topic: "udimmer/channel4/setstate"
      brightness_state_topic: "udimmer/channel4/getbrightness"
      brightness_command_topic: "udimmer/channel4/setbrightness"
      brightness_scale: 100
      retain: true
