hallway_mqtt:
  sensor:
    - platform: mqtt
      name: "Hallway Mains Frequency"
      object_id: hallway_mains_frequency
      state_topic: "udimmer/system/getfrequency"
      unit_of_measurement: "Hz"
      device_class: frequency
      state_class: measurement
  light:
    - platform: mqtt
      name: "Hallway Light"
      object_id: hallway
      state_topic: "uswitch/0x0001/channel/0x01/getvalue"
      command_topic: "uswitch/0x0001/channel/0x01/setvalue"
      retain: true
