hallway_mqtt:
  sensor:
    - platform: mqtt
      name: "Mains Frequency"
      object_id: frequency
      state_topic: "udimmer/system/getfrequency"
      unit_of_measurement: "Hz"
      device_class: frequency
      state_class: measurement
  light:
    - platform: mqtt
      name: "Hallway Light"
      object_id: hallway
      state_topic: "udimmer/channel4/getstate"
      command_topic: "udimmer/channel4/setstate"
      brightness_state_topic: "udimmer/channel4/getbrightness"
      brightness_command_topic: "udimmer/channel4/setbrightness"
      brightness_scale: 100
      retain: true
  switch:
    - platform: mqtt
      name: "Entrance Light 1"
      unique_id: entrance_light1
      availability:
        - topic: "urelay/system/getonline"
      command_topic: "urelay/switch1/setvalue"
      state_topic: "urelay/switch1/getvalue"
      optimistic: false
      qos: 0
      retain: true
    - platform: mqtt
      name: "Entrance Light 2"
      unique_id: entrance_light2
      availability:
        - topic: "urelay/system/getonline"
      command_topic: "urelay/switch2/setvalue"
      state_topic: "urelay/switch2/getvalue"
      optimistic: false
      qos: 0
      retain: true
