hallway_sensor:
  sensor:
    - platform: history_stats
      name: hallway_sensor_light_on_duration_daily
      entity_id: light.hallway
      state: "on"
      type: time
      start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
      end: "{{ now() }}"
    - platform: history_stats
      name: hallway_sensor_light_on_duration_monthly
      entity_id: light.hallway
      state: "on"
      type: time
      start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"
      end: "{{ now() }}"
    - platform: template
      sensors:
        hallway_sensor_energy_light_daily:
          friendly_name: "Hallway Sensor Energy Light Daily: "
          value_template: "{{ states('sensor.hallway_sensor_light_on_duration_daily') | float * 5 * 8 }}"
          unit_of_measurement: W
          icon_template: mdi:counter
        hallway_sensor_energy_light_monthly:
          friendly_name: "Hallway Sensor Energy Light Monthly: "
          value_template: "{{ states('sensor.hallway_sensor_light_on_duration_monthly') | float * 5 * 8 }}"
          unit_of_measurement: W
          icon_template: mdi:counter
