hallway_sensor:
  sensor:
    - platform: history_stats
      name: hallway_sensor_light_on_duration_daily
      entity_id: light.hallway
      state: "on"
      type: time
      start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
      end: "{{ now() }}"
    - platform: history_stats
      name: hallway_sensor_light_on_duration_monthly
      entity_id: light.hallway
      state: "on"
      type: time
      start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"
      end: "{{ now() }}"
    - platform: template
      sensors:
        hallway_sensor_energy_light_daily:
          friendly_name: "Hallway Sensor Energy Light Daily: "
          value_template: "{{ states('sensor.hallway_sensor_light_on_duration_daily') | float * 5 * 8 * 0.001 | round(6) }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        hallway_sensor_energy_light_monthly:
          friendly_name: "Hallway Sensor Energy Light Monthly: "
          value_template: "{{ states('sensor.hallway_sensor_light_on_duration_monthly') | float * 5 * 8 * 0.001 | round(6) }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        hallway_sensor_energy_socket_daily:
          friendly_name: "Hallway Sensor Energy Socket Daily: "
          value_template: "{{ 0 }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        hallway_sensor_energy_socket_monthly:
          friendly_name: "Hallway Sensor Energy Socket Monthly: "
          value_template: "{{ 0 }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        hallway_sensor_dew_point:
          friendly_name: "Hallway Sensor Dew Point: "
          device_class: temperature
          unit_of_measurement: C
          value_template: >-
            {% set temp = states('sensor.snzb_02_01_01_temperature') | float(0) %}
            {% set humidity = states('sensor.snzb_02_01_01_humidity') | float(0) %}
            {% if temp >= 0.0 %}
              {% set a = 7.5 %}
              {% set b = 237.3 %}
            {% else %}
              {% set a = 7.6 %}
              {% set b = 240.7 %}
            {% endif %}
            {% set sdd = (6.1078 * (10.0 ** ((a * temp) / (b + temp)))) %}
            {% set dd = (humidity / 100 * sdd) %}
            {% set v = (dd / 6.107) | log(10) %}
            {% set td = ((b * v) / (a - v)) %}
            {{ td | round(2) }}
        hallway_sensor_apparent_temperature:
          friendly_name: "Hallway Sensor Apparent Temperature: "
          device_class: temperature
          unit_of_measurement: C
          value_template: >-
            {% set temp = states('sensor.snzb_02_01_01_temperature') | float(0) %}
            {% set humidity = states('sensor.snzb_02_01_01_humidity') | float(0) %}
            {% set t = temp * 9/5 + 32 %}
            {% set rh = humidity %}
            {% set hi = 0 %}
            {% if t <= 40.0 %}
              {% set hi = t %}
            {% else %}
              {% set hi = (-42.379 + 2.04901523*t + 10.14333127*rh - 0.22475541*t*rh - 0.00683783*t*t - 0.05481717*rh*rh + 0.00122874*t*t*rh + 0.00085282*t*rh*rh - 0.00000199*t*t*rh*rh) %}
              {% if rh < 13 and t >= 80 and t <= 112 %}
                {% set adjust = ((13-rh)/4)  * ((17-((t-95)|abs)/17)|sqrt) %}
                {% set hi = hi - adjust %}
              {% elif rh > 85 and t >= 80 and t <= 87 %}
                {% set adjust = ((rh-85)/10) * ((87-t)/5) %}
                {% set hi = hi + adjust %}
              {% elif t < 80 %}
                {% set hi = 0.5 * (t + 61.0 + ((t-68.0)*1.2) + (rh*0.094)) %}
              {% endif %}
            {% endif %}
            {% set apparent_temp = (hi - 32) * 5/9 %}
            {{ apparent_temp | round(2) }}
