hallway_telegram_domofon:
  automation:
    - alias: Domofon - Test
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.domofon_state
          to: "Idle"
          for:
            seconds: 10
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "test"
            data:
              keyboard:
                - "/stop"
    - alias: Domofon - Incoming Call Notification
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.domofon_state
          to: "ring"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "_Intercom_: incoming call... {% if is_state('switch.domofon_always', 'on') or is_state('switch.domofon_once', 'on') %}(*will open automatically*){% endif %}"
            data:
              inline_keyboard:
                - "{{ '-' if is_state('switch.domofon_always', 'on') or is_state('switch.domofon_once', 'on') else 'Open:/domofon_open, Reject:/domofon_reject' }}"
    - alias: Domofon - Telegram Control - domofon_open
      initial_state: true
      trigger:
        platform: event
        event_type: telegram_callback
        event_data:
          data: "/domofon_open"
      action:
        - service: telegram_bot.answer_callback_query
          data:
            callback_query_id: "{{ trigger.event.data.id }}"
            message: "{{ 'Opening...' if is_state('sensor.domofon_state', 'ring') else 'No incoming call' }}"
        - service: switch.turn_on
          target:
            entity_id: switch.domofon_once
        - service: telegram_bot.edit_message
          data:
            chat_id: "{{ trigger.event.data.chat_id }}"
            message_id: "{{ trigger.event.data.message.message_id }}"
            message: "_Intercom_: incoming call... {% if is_state('sensor.domofon_state', 'open') %}*open!*{% endif %}"
    - alias: Domofon - Telegram Control - domofon_reject
      initial_state: true
      trigger:
        platform: event
        event_type: telegram_callback
        event_data:
          data: "/domofon_reject"
      action:
        - service: telegram_bot.answer_callback_query
          data:
            callback_query_id: "{{ trigger.event.data.id }}"
            message: "{{ 'Rejecting...' if is_state('sensor.domofon_state', 'ring') else 'No incoming call' }}"
        - service: switch.turn_on
          target:
            entity_id: switch.domofon_drop
        - wait_for_trigger:
          - platform: state
            entity_id: sensor.domofon_state
            to: "drop"
          timeout: "00:00:05"
        - service: switch.turn_off
          target:
            entity_id: switch.domofon_drop
        - service: telegram_bot.edit_message
          data:
            chat_id: "{{ trigger.event.data.chat_id }}"
            message_id: "{{ trigger.event.data.message.message_id }}"
            message: "_Intercom_: incoming call... {% if is_state('sensor.domofon_state', 'idle') %}*rejected!*{% endif %}"
    - alias: Domofon - Mute and UnMute by Time
      initial_state: true
      trigger:
        - platform: time
          at: "21:00:00"
        - platform: time
          at: "07:00:00"
      action:
        - service: >-
            {% if trigger.now.hour == 21 -%}
              switch.turn_off
            {% elif trigger.now.hour == 7 -%}
              switch.turn_on
            {% endif %}
          target:
            entity_id: switch.domofon_sound
    - alias: Domofon - Open Once for Couriers
      initial_state: true
      trigger:
        - platform: state
          entity_id:
            - sensor.oleksandr_iphone_last_notification
      condition:
        condition: or
        conditions:
          - condition: template
            value_template: >-
              {{ trigger.to_state.state | regex_search('Text .* string .*') }}
          - condition: template
            value_template: >-
              {{ trigger.to_state.state | regex_search('Message') }}
      action:
        - service: switch.turn_on
          target:
            entity_id: switch.domofon_once
        - service: notify.telegram_user_oleksandr
          data:
            message: "The courier is on the way, the one-time auto-opening mode is enabled for the intercom."
        - wait_for_trigger:
          - platform: state
            entity_id: sensor.domofon_state
            to: "open"
          - platform: state
            entity_id: sensor.domofon_state
            to: "drop"
          timeout: "00:10:00"
        - choose:
          - conditions:
            - condition: state
              entity_id: sensor.domofon_state
              state: "once"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.domofon_once
    - alias: Domofon - Open Once at Enter to Home Zone
      initial_state: true
      trigger: 
        - platform: zone
          entity_id:
            - person.oleksandr
          zone: zone.Home
          event: enter
      action:
        - choose:
          - conditions:
            - condition: state
              entity_id: switch.domofon_sound
              state: "on"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.domofon_sound
        - service: switch.turn_on
          target:
            entity_id: switch.domofon_once
        - service: notify.telegram_user_oleksandr
          data:
            message: "_Intercom_: single auto-opening mode is enabled."
        - wait_for_trigger:
          - platform: state
            entity_id: sensor.domofon_state
            to: "open"
          - platform: state
            entity_id: sensor.domofon_state
            to: "drop"
          timeout: "00:10:00"
        - choose:
          - conditions:
            - condition: time
              after: "07:00:00"
              before: "21:00:00"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.domofon_sound
        - choose:
          - conditions:
            - condition: state
              entity_id: switch.domofon_once
              state: "on"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.domofon_once
        - service: notify.telegram_user_oleksandr
          data:
            message: "_Intercom_: Disabled single auto-opening mode."
