telegram_command_menu_hallway:
  automation:
    - id: Telegram - Command Menu Hallway Control
      alias: telegram_command_menu_hallway_control
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_callback
          event_data: {}
      action:
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/hallway_control' }}"
            sequence:
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message: &msg_hallway |
                    {{ "\U0001F321" }} Temperature is {{ states('sensor.hallway_temperature') }}
                    {{ "\U0001F4A7" }} Humidity is {{ states('sensor.hallway_humidity') }}
                  inline_keyboard: &kbd_hallway
                    - "{{ '\U0001F4A1' }} Light - {% if is_state('light.hallway', 'on') %}🟢{% else %}🔴{% endif %}:/hallway_light_toggle"
                    - "{{ '\U000021A9' }} Back:/back, {{ '\U000021AA' }} Update:/hallway_control"
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/hallway_light_toggle' }}"
            sequence:
              - service: light.toggle
                target:
                  entity_id: light.hallway
              - delay:
                  milliseconds: 500
              - service: telegram_bot.answer_callback_query
                data:
                  callback_query_id: "{{ trigger.event.data.id }}"
                  message: |
                    {{ '\U0001F4AC' }} Light is {% if is_state('light.hallway', 'on') %}on{% else %}off{% endif %}
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message: *msg_hallway
                  inline_keyboard: *kbd_hallway
