hallway_telegram_domofon:
  automation:

    - alias: Domofon - Open Once for Couriers
      initial_state: true
      trigger:
        - platform: state
          entity_id:
            - sensor.oleksandr_iphone_last_notification
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: or
          conditions:
            - condition: template
              value_template: >-
                {{ trigger.to_state.state | regex_search('Text .* message .*') }}
            - condition: template
              value_template: >-
                {{ trigger.to_state.state | regex_search('Your courier is close! .*') }}
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "The courier is close!"
        - service: switch.turn_on
          target:
            entity_id: switch.domofon_once
        - service: notify.telegram_user_oleksandr
          data:
            message: "_Intercom_: single auto-opening mode is enabled."
        - wait_for_trigger:
          - platform: state
            entity_id: sensor.domofon_state
            to: "Open"
          timeout: "00:10:00"
        - wait_for_trigger:
          - platform: state
            entity_id: sensor.domofon_state
            to: "Idle"
          timeout: "00:00:05"
        - service: notify.telegram_user_oleksandr
          data:
            message: "_Intercom_: Disabled single auto-opening mode."

    - alias: Domofon - Open Once at Enter to Home Zone
      initial_state: true
      trigger: 
        - platform: zone
          entity_id:
            - person.oleksandr
          zone: zone.Home
          event: enter
      action:
        - choose:
          - conditions:
            - condition: state
              entity_id: switch.domofon_sound
              state: "on"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.domofon_sound
        - choose:
          - conditions:
            - condition: state
              entity_id: switch.domofon_once
              state: "off"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.domofon_once
              - service: notify.telegram_user_oleksandr
                data:
                  message: "_Intercom_: single auto-opening mode is enabled."
        - wait_for_trigger:
          - platform: state
            entity_id: sensor.domofon_state
            to: "Open"
          timeout: "00:10:00"
        - wait_for_trigger:
          - platform: state
            entity_id: sensor.domofon_state
            to: "Idle"
          timeout: "00:00:05"
        - choose:
          - conditions:
            - condition: time
              after: "07:00:00"
              before: "21:00:00"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.domofon_sound
        - choose:
          - conditions:
            - condition: state
              entity_id: switch.domofon_once
              state: "on"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.domofon_once
        - service: notify.telegram_user_oleksandr
          data:
            message: "_Intercom_: Disabled single auto-opening mode."
