- id: Hallway Lighting on when dark outside
  alias: turn_on_hallway_light_when_dark_outside
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      # Can be a positive or negative number
      below: -4.0
  action:
    - service: light.turn_on
      entity_id:
        - light.hallway_light

- id: Turn on light in children bedroom
  alias: turn_on_children_bedroom_light
  trigger:
    - platform: state
      entity_id: binary_sensor.children_bedroom_motion
      to: "on"
  action:
    - service: light.turn_on
      entity_id: light.children_bedroom_light
    - service: script.turn_on
      entity_id: script.send_message_motion_detected

- id: System startup report
  alias: start_message
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.telegram_user_id_1
      data:
        message: |
          {{ "\U0001F567" }} System startup at {{ states('sensor.time_date') }}

- id: Ondemand report
  alias: send_report
  initial_state: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/report'
  action:
    - service: script.turn_on
      entity_id: script.system_report

- id: Turn off all lights
  alias: turn_off_all_lights
  initial_state: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/light/all/off'
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/i/leave'
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/i/sleep'
  action:
    - service: script.turn_on
      entity_id: script.all_lights_off
    - service: notify.telegram_user_id_1
      data:
        message: "All lights are off"

- id: Telegeram start keyboard
  alias: telegram_start_keyboard
  initial_state: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/start'
  action:
    - service: notify.telegram_user_id_1
      data:
        message: "Start message"
        data:
          keyboard:
            - '/report, /light'

- id: Telegeram light keyboard
  alias: telegram_light_keyboard
  initial_state: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/light'
  action:
    - service: notify.telegram_user_id_1
      data:
        message: "All Lights"
        data:
          keyboard:
            - '/light/kitchen, /light/hallway'
            - '/light/children_bedroom, /light/parents_bedroom'
            - '/light/balcony'
            - '/start'

- id: Telegeram light-kitchen keyboard
  alias: telegram_light_kitchen_keyboard
  initial_state: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/light/kitchen'
  action:
    - service: notify.telegram_user_id_1
      data:
        message: |
          Kitchen Light is {{ states('light.kitchen') }}
        data:
          keyboard:
            - '/light/kitchen/on, /light/kitchen/off'
            - '/light'

- id: Telegeram light-kitchen-on keyboard
  alias: telegram_light_kitchen_on_keyboard
  initial_state: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/light/kitchen/on'
  action:
    - service: script.turn_on
      entity_id: script.kitchen_on
    - service: notify.telegram_user_id_1
      data:
        message: "Kitchen Light is {{ states('light.kitchen') }}"

- id: Telegeram light-kitchen-off keyboard
  alias: telegram_light_kitchen_off_keyboard
  initial_state: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/light/kitchen/off'
  action:
    - service: script.turn_off
      entity_id: scritp.kitchen_off
    - service: notify.telegram_user_id_1
      data:
        message: "Kitchen Light is {{ states('light.kitchen') }}"
