- id: 1
  alias: "Turn on the light in children bedroom"
  trigger:
    - platform: state
      entity_id: binary_sensor.children_bedroom_motion
      to: "ON"
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.children_bedroom_light
