- id: Hallway Lighting on when dark outside
  alias: turn_on_hallway_light_when_dark_outside
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      # Can be a positive or negative number
      below: -4.0
  action:
    - service: light.turn_on
      entity_id:
        - light.hallway

- id: Turn on light in children bedroom
  alias: turn_on_children_bedroom_light
  trigger:
    - platform: state
      entity_id: binary_sensor.children_bedroom_motion
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: device_tracker.oleksandr_iphone
      state: "not_home"
  action:
    - service: light.turn_on
      entity_id: light.children_bedroom
    - service: script.turn_on
      entity_id: script.send_message_motion_detected
