- id: Hallway Lighting on when dark outside
  alias: turn_on_hallway_light_when_dark_outside
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      # Can be a positive or negative number
      below: -4.0
  action:
    - service: light.turn_on
      entity_id:
        - light.hallway_light

- id: Turn on light in children bedroom
  alias: turn_on_children_bedroom_light
  trigger:
    - platform: state
      entity_id: binary_sensor.children_bedroom_motion
      to: "on"
  action:
    - service: light.turn_on
      entity_id:
        - light.children_bedroom_light
    - service: script.turn_on
      entity_id: script.send_message_motion_detected

- id: System startup report
  alias: start_message
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.telegram_user_id_1
      data:
        message: |
          {{ "\U0001F567" }} System startup at {{ states('sensor.time_date') }}

- id: Ondemand report
  alias: send_report
  initial_state: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/report'
  action:
    - service: script.turn_on
      entity_id: script.system_report

- id: All Lights Off
  alias: all_lights_off
  initial_state: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/light/all/off'
  action:
    - service: script.turn_on
      entity_id: script.all_lights_off
    - service: notify.telegram_user_id_1
      data:
        message: "All lights are off"
