sensor_temperature:
  - platform: mqtt
    name: "Children Bedroom Temperature"
    state_topic: "usensor/temperature/getvalue"
    unit_of_measurement: "ºC"
    
sensor_humidity:
  - platform: mqtt
    name: "Children Bedroom Humidity"
    state_topic: "usensor/humidity/getvalue"
    unit_of_measurement: "%"
