homeassistant:
  name: "My Home Assistant Instance"
  latitude: 50.511079642761075
  longitude: 30.79095544917174
  elevation: 0
  unit_system: metric
  time_zone: "Europe/Kiev"

frontend:
config:
discovery:
conversation:
#history:
sun:
homekit:

tts:
  - platform: google_translate

mqtt:
  broker: localhost
  username: mosquitto
  password: password
  discovery: true
  discovery_prefix: homeassistant

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_user_id_1

automation: !include automation.yaml
#zone: !include zone.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
#switch: !include switch.yaml
#device_tracker: !include device_tracker.yaml
light: !include light.yaml
script: !include script.yaml
notify: !include notify.yaml
