homeassistant:
  name: "My Home Assistant Instance"
  latitude: 50.511079642761075
  longitude: 30.79095544917174
  unit_system: metric
  time_zone: "Europe/Kiev"
  #customize: !include customize.yaml

frontend:

mqtt:
  broker: localhost
  username: mosquitto
  password: password

#automation: !include automation.yaml
#zone: !include zone.yaml
sensor: !include sensor.yaml
#switch: !include switch.yaml
#device_tracker: !include device_tracker.yaml

light: !include light.yaml
