sensor:
  - platform: mqtt
    name: "Children Bedroom Temperature"
    state_topic: "usensor/temperature/getvalue"
    unit_of_measurement: "ºC"

  - platform: mqtt
    name: "Children Bedroom Humidity"
    state_topic: "usensor/humidity/getvalue"
    unit_of_measurement: "%"

light:
  - platform: mqtt
    schema: template
    name: "Kitchen Light"
    state_topic: "udimmer/channel1/geton"
    state_template: "{% if value == 'true' %}on{% else %}off{% endif %}"
    command_topic: "udimmer/channel1/seton"
    command_on_template: "true"
    command_off_template: "false"
    brightness_state_topic: "udimmer/channel1/getbrightness"
    brightness_command_topic: "udimmer/channel1/setbrightness"
    brightness_scale: 127
    qos: 1
    retain: true
    optimistic: false

  - platform: mqtt
    schema: template
    name: "Children Bedroom Light"
    state_topic: "udimmer/channel2/geton"
    state_template: "{% if value == 'true' %}on{% else %}off{% endif %}"
    command_topic: "udimmer/channel2/seton"
    command_on_template: "true"
    command_off_template: "false"
    brightness_state_topic: "udimmer/channel2/getbrightness"
    brightness_command_topic: "udimmer/channel2/setbrightness"
    brightness_scale: 127
    qos: 1
    retain: true
    optimistic: false
    
  - platform: mqtt
    schema: template
    name: "Parents Bedroom Light"
    state_topic: "udimmer/channel3/geton"
    state_template: "{% if value == 'true' %}on{% else %}off{% endif %}"
    command_topic: "udimmer/channel3/seton"
    command_on_template: "true"
    command_off_template: "false"
    brightness_state_topic: "udimmer/channel3/getbrightness"
    brightness_command_topic: "udimmer/channel3/setbrightness"
    brightness_scale: 127
    qos: 1
    retain: true
    optimistic: false
    
    
