homeassistant:
  name: "Home Assistant"
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: "Europe/Kiev"
  external_url: "http://192.168.0.111:8123"
  internal_url: "http://127.0.0.1:8123"
  packages: !include_dir_merge_named packages

config:
#ssdp:
frontend:
map:
#history:
#logbook:
mobile_app:
sun:

#zone: !include zone.yaml
sensor: !include sensor.yaml
#binary_sensor: !include binary_sensor.yaml
#switch: !include switch.yaml
#device_tracker: !include device_tracker.yaml
#light: !include light.yaml
script: !include script.yaml
#notify: !include notify.yaml
#automation: !include automation.yaml
