homeassistant:
  name: "Home Assistant"
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: "Europe/Kiev"
  external_url: "http://192.168.0.111:8123"
  internal_url: "http://192.168.0.111:8123"
  packages: !include_dir_merge_named packages

lovelace:
  mode: yaml
  resources:
    - url: /local/auto-entities.js
      type: module
    - url: /local/stack-in-card.js
      type: module
    - url: /local/battery-state-card.js
      type: module
    - url: /local/multiple-entity-row.js
      type: module
    - url: /local/mushroom.js
      type: module

config:
#ssdp:
system_health:
frontend:
map:
history:
recorder:
  auto_purge: true
  purge_keep_days: 1460
  commit_interval: 60
  include:
    domains:
      - light
    entity_globs:
      - sensor.*_humidity
      - sensor.*_temperature
      - binary_sensor.*_contact
      - binary_sensor.*_occupancy
  exclude:
    entities:
      - light.balcony
      - light.entrance
logbook:
media_source:
mobile_app:
sun:
energy:

#zone: !include zone.yaml
sensor: !include sensor.yaml
#binary_sensor: !include binary_sensor.yaml
#switch: !include switch.yaml
#device_tracker: !include device_tracker.yaml
#light: !include light.yaml
script: !include script.yaml
#notify: !include notify.yaml
#automation: !include automation.yaml
