system_report:
  alias: Report of system state
  sequence:
    - service: notify.telegram_user_id_1
      data:
        message: |
          {{ "\U0001F4AC" }} System State
          {{ "\U0001F4A1" }} Lights: {{ states('sensor.all_lights') }} / {{ states('sensor.unavailable_lights') }}
          {{ "\U0001F50C" }} Switches: {{ states('sensor.all_switches') }} / {{ states('sensor.unavailable_switches') }}
          {{ "\U0001F321" }} Sensors: {{ states('sensor.all_sensors') }} / {{ states('sensor.unavailable_sensors') }}
          {{ "\U0001F51F" }} Binary Sensors: {{ states('sensor.all_binary_sensors') }} / {{ states('sensor.unavailable_binary_sensors') }}

send_message_1:
  alias: Send via notification service
  sequence:
    - service: notify.telegram_user_id_1
      data:
        message: "Current time - {{ states('sensor.time') }}. All right."

send_message_motion_detected:
  alias: Motion detection notifier
  sequence:
    - service: notify.telegram_user_id_1
      data:
        message: |
          Motion Detected!
          Time: {{ states('sensor.time') }}

all_lights_off:
  sequence:
    sequence:
    - service: light.turn_on
      entity_id:
        - light.hallway
        - light.kitchen
        - light.children_bedroom
        - light.parents_bedroom
        - light.balcony
