kitchen_on:
  sequence:
    - service: light.turn_on
      entity_id: light.kitchen

kitchen_off:
  sequence:
    - service: light.turn_off
      entity_id: light.kitchen

all_lights_off:
  sequence:
    - service: light.turn_off
      entity_id:
        - light.hallway
        - light.kitchen
        - light.children_bedroom
        - light.parents_bedroom
        - light.balcony
