all_lights_off:
  sequence:
    - service: light.turn_off
      target:
        entity_id:
          - light.hallway
          - light.kitchen
          - light.kids_bedroom
          - light.parents_bedroom
          - light.balcony
