report_system:
  alias: Report of system state
  sequence:
    - service: notify.telegram_user_id_1
      data:
        message: |
          {{ "\U0001F4AC" }} System State
          {{ "\U0001F4A1" }} Lights: {{ states('sensor.all_lights') }} / {{ states('sensor.unavailable_lights') }}
          {{ "\U0001F50C" }} Switches: {{ states('sensor.all_switches') }} / {{ states('sensor.unavailable_switches') }}
          {{ "\U0001F321" }} Sensors: {{ states('sensor.all_sensors') }} / {{ states('sensor.unavailable_sensors') }}
          {{ "\U0001F51F" }} Binary Sensors: {{ states('sensor.all_binary_sensors') }} / {{ states('sensor.unavailable_binary_sensors') }}

report_light:
  alias: Report of light state
  sequence:
    - service: notify.telegram_user_id_1
      data:
        message: |
          {{ "\U0001F4AC" }} Light State
          {{ "\U0001F4A1" }} Hallway is {{ states('light.hallway') }}
          {{ "\U0001F4A1" }} Kitchen is {{ states('light.kitchen') }}
          {{ "\U0001F4A1" }} Children Bedroom is {{ states('light.children_bedroom') }}
          {{ "\U0001F4A1" }} Parent Bedroom is {{ states('light.parent_bedroom') }}
          {{ "\U0001F4A1" }} Balcony is {{ states('light.balcony') }}

send_message_1:
  alias: Send via notification service
  sequence:
    - service: notify.telegram_user_id_1
      data:
        message: "Current time - {{ states('sensor.time') }}. All right."

send_message_motion_detected:
  alias: Motion detection notifier
  sequence:
    - service: notify.telegram_user_id_1
      data:
        message: |
          Motion Detected!
          Time: {{ states('sensor.time') }}

kitchen_on:
  sequence:
    - service: light.turn_on
      entity_id: light.kitchen

kitchen_off:
  sequence:
    - service: light.turn_off
      entity_id: light.kitchen

all_lights_off:
  sequence:
    - service: light.turn_off
      entity_id:
        - light.hallway
        - light.kitchen
        - light.children_bedroom
        - light.parents_bedroom
        - light.balcony
