title: Home Assistant
views:
  - !include lovelace/001_overview.yaml
  - !include lovelace/111_hallway_control.yaml
  - !include lovelace/121_kitchen_control.yaml
  - !include lovelace/131_kids_bedroom_control.yaml
  - !include lovelace/141_parents_bedroom_control.yaml
