##################   Control   ##################
title: Hallway
icon: phu:rooms-living
cards:

############################ Column 1 ############################

    - type: vertical-stack
      cards:
      
        - type: markdown
          style: |
              ha-card {
                font-size: 26px;
              }          
          content: >
             **Control**
             
        - type: custom:stack-in-card
          mode: vertical
          cards:  
            - type: markdown
              style: |
                   ha-card {
                     color: #f8ffd8;
                     --paper-item-icon-color: #f8ffd8;
                     --paper-item-icon-active-color: #f8ffd8;
                     font-weight: bold;
                     font-size: 14px;
                   } 
              content: >
                 **Lights**
            - type: horizontal-stack
              cards:

                - type: button
                  name: Main Light
                  entity: light.hallway
                  tap_action:
                    action: toggle   

            - type: conditional
              conditions:
                - entity: light.hallway
                  state: "on"
              card:
                  type: custom:mushroom-light-card
                  entity: light.hallway
                  name: Main Light
                  icon_type: none
                  primary_info: name
                  secondary_info: none
                  use_light_color: true
                  show_brightness_control: true
                  show_color_temp_control: true
                  show_color_control: false
                  collapsible_controls: true

############################ Column 2 ############################

    - type: vertical-stack
      cards:

        - type: markdown
          style: |
              ha-card {
                font-size: 26px;
              }   
          content: >
              **Monitoring** 
        - type: custom:stack-in-card
          mode: vertical
          cards: 

            - type: markdown
              content: >
                 **Sensors**
            - type: glance
              show_state: true
              show_name: true
              state_color: true
              entities:
              - entity: binary_sensor.snzb_04_01_contact
                name: Door
              - entity: binary_sensor.snzb_03_01_occupancy
                name: Motion
              - entity: sensor.snzb_02_01_01_temperature
                name: Temperature
              - entity: sensor.snzb_02_01_01_humidity
                name: Humidity

                    
############################ Column 3 ############################

    - type: vertical-stack
      cards:
      
        - type: markdown
          style: |
              ha-card {
                font-size: 26px;
              }          
          content: >
             **Telemetry**
                
        - type: custom:stack-in-card
          mode: vertical
          cards: 

            - type: markdown
              content: >
                 **Sensors**
             
            - type: entities
              show_header_toggle: false
              entities:
                - entity: sensor.snzb_01_01_battery
                  type: custom:multiple-entity-row
                  icon: mdi:light-switch
                  state_color: true
                  name: Switch
                  secondary_info: last-changed
                  state_header: Battery
                  entities:
                  - attribute: linkquality
                    name: Signal
                - type: divider
                - entity: sensor.snzb_02_01_01_battery
                  type: custom:multiple-entity-row
                  icon: mdi:coolant-temperature
                  state_color: true
                  name: Climate Sensor
                  secondary_info: last-changed
                  state_header: Battery
                  entities:
                  - attribute: linkquality
                    name: Signal
                - type: divider
                - entity: sensor.0x04cf8cdf3c7cf19e_battery
                  type: custom:multiple-entity-row
                  icon: mdi:sun-wireless
                  state_color: true
                  name: Light Sensor
                  secondary_info: last-changed
                  state_header: Battery
                  entities:
                  - attribute: linkquality
                    name: Signal
                - type: divider
                - entity: sensor.snzb_03_01_battery
                  type: custom:multiple-entity-row
                  icon: mdi:run
                  state_color: true
                  name: Motion Sensor
                  secondary_info: last-changed
                  state_header: Battery
                  entities:
                  - attribute: linkquality
                    name: Signal
                - type: divider
                - entity: sensor.snzb_04_01_battery
                  type: custom:multiple-entity-row
                  icon: mdi:window-open-variant
                  state_color: true
                  name: Door Sensor
                  secondary_info: last-changed
                  state_header: Battery
                  entities:
                  - attribute: linkquality
                    name: Signal
