all_automation:
  automation:
    - id: all_automation_light_on_me_away
      alias: All - Automation - Light On - Me Away
      initial_state: true
      trigger:
        - platform: zone
          entity_id: person.oleksandr
          zone: zone.home
          # Event is either enter or leave
          event: leave
      condition:
        - or:
          - condition: state
            entity_id: light.hallway
            state: "on"
          - condition: state
            entity_id: light.kitchen
            state: "on"
          - condition: state
            entity_id: light.kids_bedroom
            state: "on"
          - condition: state
            entity_id: light.parents_bedroom
            state: "on"
      action:
        - service: light.turn_off
          target:
            entity_id:
              - light.hallway
              - light.kitchen
              - light.kids_bedroom
              - light.parents_bedroom
