all_sensor:
  sensor:

    - platform: template
      sensors:
        outdoor_temperature:
          friendly_name: "Outdoor, Temperature"
          unit_of_measurement: "°C"
          device_class: temperature
          value_template: "{{ state_attr('weather.home', 'temperature') }}"
        outdoor_humidity:
          friendly_name: "Outdoor, Humidity"
          unit_of_measurement: "%"
          device_class: humidity
          value_template: "{{ state_attr('weather.home', 'humidity') }}"

    - platform: template
      sensors:
        all_sensor_energy_total_daily:
          friendly_name: "All Sensor Energy Total Daily: "
          value_template: "{{ states('sensor.all_sensor_energy_light_daily') | float + states('sensor.all_sensor_energy_socket_daily') | float }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        all_sensor_energy_total_monthly:
          friendly_name: "All Sensor Energy Total Monthly: "
          value_template: "{{ states('sensor.all_sensor_energy_light_monthly') | float + states('sensor.all_sensor_energy_socket_monthly') | float }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        all_sensor_energy_light_daily:
          friendly_name: "All Sensor Energy Light Daily: "
          value_template: "{{ (states('sensor.hallway_sensor_energy_light_daily') | float + states('sensor.kitchen_sensor_energy_light_daily') | float + states('sensor.kids_bedroom_sensor_energy_light_daily') | float + states('sensor.parents_bedroom_sensor_energy_light_daily') | float) | round(2) }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        all_sensor_energy_light_monthly:
          friendly_name: "All Sensor Energy Light Monthly: "
          value_template: "{{ (states('sensor.hallway_sensor_energy_light_monthly') | float + states('sensor.kitchen_sensor_energy_light_monthly') | float + states('sensor.kids_bedroom_sensor_energy_light_monthly') | float + states('sensor.parents_bedroom_sensor_energy_light_monthly') | float) | round(2) }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        all_sensor_energy_socket_daily:
          friendly_name: "All Sensor Energy Socket Daily: "
          value_template: "{{ (states('sensor.hallway_sensor_energy_socket_daily') | float + states('sensor.kitchen_sensor_energy_socket_daily') | float + states('sensor.kids_bedroom_sensor_energy_socket_daily') | float + states('sensor.parents_bedroom_sensor_energy_socket_daily') | float) | round(2) }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        all_sensor_energy_socket_monthly:
          friendly_name: "All Sensor Energy Socket Monthly: "
          value_template: "{{ (states('sensor.hallway_sensor_energy_socket_monthly') | float + states('sensor.kitchen_sensor_energy_socket_monthly') | float + states('sensor.kids_bedroom_sensor_energy_socket_monthly') | float + states('sensor.parents_bedroom_sensor_energy_socket_monthly') | float) | round(2) }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter

        daily_total_energy:
          friendly_name: "Daily Total Energy: "
          value_template: "{{ states('sensor.daily_total_energy_peak') | float + states('sensor.daily_total_energy_offpeak') | float }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter          
        daily_total_energy_peak_percent:
          friendly_name: "Daily Total Energy Peak Percent: "
          value_template: "{{ (states('sensor.daily_total_energy_peak') | float / (states('sensor.daily_total_energy') | float / 100)) | round(2) }}"
          icon_template: mdi:counter
        daily_total_energy_offpeak_percent:
          friendly_name: "Daily Total Energy Offpeak Percent: "
          value_template: "{{ (states('sensor.daily_total_energy_offpeak') | float / (states('sensor.daily_total_energy') | float / 100)) | round(2) }}"
          icon_template: mdi:counter

        monthly_total_energy:
          friendly_name: "Monthly Total Energy: "
          value_template: "{{ states('sensor.monthly_total_energy_peak') | float + states('sensor.monthly_total_energy_offpeak') | float }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        monthly_total_energy_peak_percent:
          friendly_name: "Monthly Total Energy Peak Percent: "
          value_template: "{{ (states('sensor.monthly_total_energy_peak') | float / (states('sensor.monthly_total_energy') | float / 100)) | round(2) }}"
          icon_template: mdi:counter
        monthly_total_energy_offpeak_percent:
          friendly_name: "Monthly Total Energy Offpeak Percent: "
          value_template: "{{ (states('sensor.monthly_total_energy_offpeak') | float / (states('sensor.monthly_total_energy') | float / 100)) | round(2) }}"
          icon_template: mdi:counter

        daily_total_energy_money:
          friendly_name: "Daily Total Energy Money: "
          value_template: "{{ states('sensor.daily_total_energy_peak_money') | float + states('sensor.daily_total_energy_offpeak_money') | float }}"
          unit_of_measurement: 'UAH'
          icon_template: mdi:square-inc-cash
        daily_total_energy_peak_money:
          friendly_name: "Daily Total Energy Peak Money: "
          value_template: "{{ (states('sensor.daily_total_energy_peak') | float * 1.68) | round(2) }}"
          unit_of_measurement: 'UAH'
          icon_template: mdi:square-inc-cash
        daily_total_energy_offpeak_money:
          friendly_name: "Daily Total Energy Offpeak Money: "
          value_template: "{{ (states('sensor.daily_total_energy_offpeak') | float * 0.84) | round(2) }}"
          unit_of_measurement: 'UAH'
          icon_template: mdi:square-inc-cash

        monthly_total_energy_money:
          friendly_name: "Monthly Total Energy Money: "
          value_template: "{{ states('sensor.monthly_total_energy_peak_money') | float + states('sensor.monthly_total_energy_offpeak_money') | float }}"
          unit_of_measurement: 'UAH'
          icon_template: mdi:square-inc-cash
        monthly_total_energy_peak_money:
          friendly_name: "Monthly Total Energy Peak Money: "
          value_template: >
            {% if states('sensor.monthly_total_energy') | float <= 250.0 %}
              {{ (states('sensor.monthly_total_energy') | float * 1.44 * 1.0 * (states('sensor.monthly_total_energy_peak_percent') | float / 100.0)) | round(2) }}
            {% else %}
              {{ ((250.0 * 1.44 * 1.0 * (states('sensor.monthly_total_energy_peak_percent') | float / 100.0)) + (states('sensor.monthly_total_energy') | float - 250.0) * 1.68 * 1.0 * (states('sensor.monthly_total_energy_peak_percent') | float / 100.0)) | round(2) }}
            {% endif %}
          unit_of_measurement: 'UAH'
          icon_template: mdi:square-inc-cash
        monthly_total_energy_offpeak_money:
          friendly_name: "Monthly Total Energy Offpeak Money: "
          value_template: >
            {% if states('sensor.monthly_total_energy') | float <= 250.0 %}
              {{ (states('sensor.monthly_total_energy') | float * 1.44 * 0.5 * (states('sensor.monthly_total_energy_offpeak_percent') | float / 100.0)) | round(2) }}
            {% else %}
              {{ ((250.0 * 1.44 * 0.5 * (states('sensor.monthly_total_energy_offpeak_percent') | float / 100.0)) + (states('sensor.monthly_total_energy') | float - 250.0) * 1.68 * 0.5 * (states('sensor.monthly_total_energy_offpeak_percent') | float / 100.0)) | round(2) }}
            {% endif %}
          unit_of_measurement: 'UAH'
          icon_template: mdi:square-inc-cash
