all_sensor:
  sensor:
    - platform: template
      sensors:
        all_sensor_energy_light_daily:
          friendly_name: "All Sensor Energy Light Daily: "
          value_template: "{{ states('sensor.hallway_sensor_energy_light_daily') | float + states('sensor.kitchen_sensor_energy_light_daily') | float + states('sensor.kids_bedroom_sensor_energy_light_daily') | float + states('sensor.parents_bedroom_sensor_energy_light_daily') | float }}"
          unit_of_measurement: W
          icon_template: mdi:counter
        all_sensor_energy_light_monthly:
          friendly_name: "All Sensor Energy Light Monthly: "
          value_template: "{{ states('sensor.hallway_sensor_energy_light_monthly') | float + states('sensor.kitchen_sensor_energy_light_monthly') | float + states('sensor.kids_bedroom_sensor_energy_light_monthly') | float + states('sensor.parents_bedroom_sensor_energy_light_monthly') | float }}"
          unit_of_measurement: W
          icon_template: mdi:counter
