entrance_automation_zone:
  automation:

    - id: entrance_automation_domofon_open_once_at_enter_to_home_zone
      alias: Entrance - Automation - Domofon - Open Once at Enter to Home Zone
      initial_state: true
      trigger: 
        - platform: zone
          entity_id:
            - person.oleksandr
          zone: zone.Home
          event: enter
      action:
        - choose:
          - conditions:
            - condition: state
              entity_id: switch.domofon_sound
              state: "on"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.domofon_sound
        - choose:
          - conditions:
            - condition: state
              entity_id: select.domofon_mode
              state:
                - "always"
                - "drop"
                - "never"
            sequence:
              - service: input_select.select_option
                target:
                  entity_id: select.domofon_mode
                data:
                  option: "once"
              - service: notify.telegram_user_oleksandr
                data:
                  message: "_Intercom_: single auto-opening mode is enabled."
        - wait_for_trigger:
          - platform: state
            entity_id: sensor.domofon_state
            to: "Open"
          timeout: "00:10:00"
        - wait_for_trigger:
          - platform: state
            entity_id: sensor.domofon_state
            to: "Idle"
          timeout: "00:00:05"
        - choose:
          - conditions:
            - condition: time
              after: "07:00:00"
              before: "21:00:00"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.domofon_sound
        - choose:
          - conditions:
            - condition: state
              entity_id: select.domofon_mode
              state: "once"
            sequence:
              - service: input_select.select_option
                target:
                  entity_id: select.domofon_mode
                data:
                  option: "never"
        - service: notify.telegram_user_oleksandr
          data:
            message: "_Intercom_: Disabled single auto-opening mode."
  
    - id: entrance_automation_enter_to_home_zone
      alias: Entrance - Automation - Enter to Home Zone
      initial_state: true
      trigger: 
        - platform: zone
          entity_id:
            - person.oleksandr
          zone: zone.Home
          event: enter
      condition:
        - condition: or
          conditions:
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
      action:
        - service: light.turn_on
          target:
            entity_id: light.entrance
          data:
            brightness_pct: 15

    - id: entrance_automation_leave_from_home_zone
      alias: Entrance - Automation - Leave from Home Zone
      initial_state: true
      trigger: 
        - platform: zone
          entity_id:
            - person.oleksandr
          zone: zone.Home
          event: leave
      condition:
        - condition: or
          conditions:
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
      action:
        - service: light.turn_off
          target:
            entity_id: light.entrance
