entrance_automation_zone:
  automation:
  
    - alias: Entrance - Automation - Enter to Home Zone
      initial_state: true
      trigger: 
        - platform: zone
          entity_id:
            - person.oleksandr
          zone: zone.Home
          event: enter
      condition:
        - condition: or
          conditions:
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
      action:
        - service: light.turn_on
          target:
            entity_id: light.entrance
          data:
            brightness_pct: 15

    - alias: Entrance - Automation - Leave from Home Zone
      initial_state: true
      trigger: 
        - platform: zone
          entity_id:
            - person.oleksandr
          zone: zone.Home
          event: leave
      condition:
        - condition: or
          conditions:
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
      action:
        - service: light.turn_off
          target:
            entity_id: light.entrance
