entrance_automation_time:
  automation:

    - id: entrance_automation_domofon_mute_and_unmute_by_time
      alias: Entrance - Automation - Domofon - Mute and UnMute by Time
      initial_state: true
      trigger:
        - platform: time
          at: "21:00:00"
        - platform: time
          at: "07:00:00"
      action:
        - service: >-
            {% if trigger.now.hour == 21 -%}
              switch.turn_off
            {% elif trigger.now.hour == 7 -%}
              switch.turn_on
            {% endif %}
          target:
            entity_id: switch.domofon_sound

    - id: entrance_automation_sunset
      alias: Entrance - Automation - Sunset
      initial_state: false
      trigger:
        - platform: sun
          event: sunset
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: home
      action:
        - service: light.turn_on
          target:
            entity_id: light.entrance
#          data:
#            brithness_pct: 15

    - id: entrance_automation_sunrise
      alias: Entrance - Automation - Sunrise
      initial_state: false
      trigger:
        - platform: sun
          event: sunrise
          offset: 02:00:00
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: home
      action:
        - service: light.turn_off
          target:
            entity_id: light.entrance

    - id: entrance_automation_domofon_open_when_dark_notification
      alias: Entrance - Automation - Domofon - Open When Dark Notification
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.domofon_state
          to: open
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: home
        - or:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
      action:
        - if:
          - condition: state
            entity_id: light.hallway
            state: "off"
          then:
            - service: light.turn_on
              target:
                entity_id: light.hallway
        - if:
          - condition: state
            entity_id: light.entrance
            state: "off"
          then:
            - service: light.turn_on
              target:
                entity_id: light.entrance
