entrance_automation_zone:
  automation:
    - alias: Entrance - Enter to Home Zone
      initial_state: true
      trigger: 
        - platform: zone
          entity_id:
            - person.oleksandr
          zone: zone.Home
          event: enter
      condition:
        - condition: or
          conditions:
            - condition: sun
              after: sunset
              after_offset: "+00:30:00"
            - condition: sun
              before: sunrise
              before_offset: "-00:30:00"
      action:
        - service: light.turn_on
          target:
            entity_id: light.entrance
          data:
            brightness_pct: 15
