entrance_automation:
  automation:
    - id: entrance_light_auto_turn_on_for_motion_when_dark
      alias: Turn on light in entrance for motion when dark
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.entrance_motion
          to: "on"
      condition:
        - condition: or
          conditions:
            - condition: sun
              after: sunrise
              after_offset: "+00:30:00"
            - condition: sun
              before: sunset
              before_offset: "-00:30:00"
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: state
          entity_id: light.entrance
          state: "off"
      action:
        - service: light.turn_on
          target:
            entity_id: light.entrance
        - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.entrance_motion
            to: "off"
        - service: light.turn_off
          target:
            entity_id: light.entrance
