entrance_customize:
    homeassistant:
      customize:
        sensor.domofon_state:
          friendly_name: Entrance, Domofon
        sensor.domofon_battery:
          friendly_name: Entrance, Domofon
