entrance_telegram_domofon:
  automation:
  
    - id: domofon_open_when_dark_notification
      alias: Domofon - Open When Dark Notification
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.domofon_state
          to: "Open"
      condition:
        - condition: or
          conditions:
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
        - condition: or
          conditions:
            - condition: state
              entity_id: light.entrance
              state: "off"
            - condition: numeric_state
              entity_id: light.entrance
              attribute: brightness
              below: 125
      action:
        - service: light.turn_on
          target:
            entity_id: light.entrance
          data:
            brightness_pct: 50
        - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.entrance_motion
            to: "on"
          timeout: "00:02:00"
        - if:
            - "{{ not wait.completed }}"
          then:
            - service: light.turn_on
              target:
                entity_id: light.entrance
              data:
                brightness_pct: 15

