entrance_telegram_command_menu:
  automation:

    - id: entrance_telegram_command_menu_control
      alias: Entrance - Telegram - Command Menu Control
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_callback
          event_data: {}
      action:
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/entrance_control' }}"
            sequence:
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message: &msg_entrance |
                    Domofon Mode - {{ states('select.domofon_mode') }}
                    Domofon State - {{ states('sensor.domofon_state') }}
                    {{ "\U000026A1" }} Mains Current is {{ states('sensor.entrance_mains_frequency') }}
                    {{ "\U000026A1" }} Motion is {{ states('binary_sensor.entrance_motion') }}
                    {{ "\U0001F321" }} Temperature is {{ states('sensor.entrance_temperature') }}
                    {{ "\U0001F4A7" }} Humidity is {{ states('sensor.entrance_humidity') }}
                  inline_keyboard: &kbd_entrance
                    - "{{ '\U0001F4A1' }} Light - {% if is_state('light.entrance', 'on') %}🟢{% else %}🔴{% endif %}:/entrance_light_toggle"
                    - "{{ '\U0001F4A1' }} Domofon Once - {% if is_state('switch.domofon_once', 'on') %}🟢{% else %}🔴{% endif %}:/entrance_domofon_once_toggle"
                    - "{{ '\U0001F4A1' }} Domofon Sound - {% if is_state('switch.domofon_sound', 'on') %}🟢{% else %}🔴{% endif %}:/entrance_domofon_sound_toggle"
                    - "{{ '\U000021A9' }} Back:/back, {{ '\U000021AA' }} Update:/entrance_control"
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/entrance_domofon_once_toggle' }}"
            sequence:
              - service: switch.toggle
                target:
                  entity_id: switch.domofon_once
              - delay:
                  milliseconds: 500
              - service: telegram_bot.answer_callback_query
                data:
                  callback_query_id: "{{ trigger.event.data.id }}"
                  message: |
                    {{ '\U0001F4AC' }} Domofon Once is {% if is_state('switch.domofon_once', 'on') %}on{% else %}off{% endif %}
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message: *msg_entrance
                  inline_keyboard: *kbd_entrance
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/entrance_domofon_sound_toggle' }}"
            sequence:
              - service: switch.toggle
                target:
                  entity_id: switch.domofon_sound
              - delay:
                  milliseconds: 500
              - service: telegram_bot.answer_callback_query
                data:
                  callback_query_id: "{{ trigger.event.data.id }}"
                  message: |
                    {{ '\U0001F4AC' }} Domofon Sound is {% if is_state('switch.domofon_sound', 'on') %}on{% else %}off{% endif %}
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message: *msg_entrance
                  inline_keyboard: *kbd_entrance
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/entrance_light_toggle' }}"
            sequence:
              - service: light.toggle
                target:
                  entity_id: light.entrance
              - delay:
                  milliseconds: 500
              - service: telegram_bot.answer_callback_query
                data:
                  callback_query_id: "{{ trigger.event.data.id }}"
                  message: |
                    {{ '\U0001F4AC' }} Light is {% if is_state('light.entrance', 'on') %}on{% else %}off{% endif %}
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message: *msg_entrance
                  inline_keyboard: *kbd_entrance
