kids_bedroom_automation:
  automation:
    - id: kids_bedroom_automation_motion_on_me_home
      alias: Kids Bedroom - Automation - Motion On - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.sonoff_motion_03_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_on
          target:
            entity_id: light.kids_bedroom

    - id: kids_bedroom_automation_motion_on_me_away
      alias: Kids Bedroom - Automation - Motion On - Me Away
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.sonoff_motion_03_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "not_home"
      action:
        - service: light.turn_on
          target:
            entity_id: light.kids_bedroom
        - service: notify.telegram_user_oleksandr
          data:
            message: "Security: Motion detected in the kids bedroom."

    - id: kids_bedroom_automation_motion_off_me_home
      alias: Kids Bedroom - Automation - Motion Off - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.sonoff_motion_03_occupancy
          from: "on"
          to: "off"
          for:
            minutes: 4
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.turn_off
          target:
            entity_id: light.kids_bedroom

    - id: kids_bedroom_automation_switch_single_press
      alias: Kids Bedroom - Automation - Switch - Single Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.sonoff_switch_03_action
          to: "single"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.toggle
          target:
            entity_id: light.kids_bedroom

    - id: kids_bedroom_automation_switch_long_press
      alias: Kids Bedroom - Automation - Switch - Long Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.sonoff_switch_03_action
          to: "long"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: script.turn_on
          target:
              entity_id: script.all_lights_off
        - service: notify.telegram_user_oleksandr
          data:
            message: "Automation: All lights are off."
