kids_bedroom_automation:
  automation:
    - id: kids_bedroom_automation_motion
      alias: Kids Bedroom - Automation - Motion
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.0x00124b00251c48ec_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "not_home"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Security: Motion detected in the kids bedroom."

    - id: kids_bedroom_automation_switch_long_press
      alias: Kids Bedroom - Automation - Switch - Long Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.0x00124b002268ac57_action
          to: "long"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: script.turn_on
          target:
              entity_id: script.all_lights_off
        - service: notify.telegram_user_oleksandr
          data:
            message: "Automation: All lights are off."
