kids_bedroom_automation:
  automation:
    - id: kids_bedroom_automation_motion_on_me_home
      alias: Kids Bedroom - Automation - Motion On - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_03_occupancy
          to: "on"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 4
      action:
        - service: light.turn_on
          target:
            entity_id: light.kids_bedroom

    - id: kids_bedroom_automation_motion_off_me_home
      alias: Kids Bedroom - Automation - Motion Off - Me Home
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.snzb_03_03_occupancy
          from: "on"
          to: "off"
          for:
            minutes: 4
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          above: 4
        - condition: state
          entity_id: light.kids_bedroom
          state: "on"
      action:
        - service: light.turn_off
          target:
            entity_id: light.kids_bedroom

    - id: kids_bedroom_automation_switch_single_press
      alias: Kids Bedroom - Automation - Switch - Single Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_03_action
          to: "single"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: light.toggle
          target:
            entity_id: light.kids_bedroom

    - id: kids_bedroom_automation_switch_long_press
      alias: Kids Bedroom - Automation - Switch - Long Press
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.snzb_01_03_action
          to: "long"
      condition:
        - condition: state
          entity_id: person.oleksandr
          state: "home"
      action:
        - service: script.turn_on
          target:
              entity_id: script.all_lights_off
