kids_bedroom_mqtt:
  sensor:
    - platform: mqtt
      name: "Kids Bedroom Temperature"
      object_id: temperature
      state_topic: "usensor/temperature/getvalue"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
    - platform: mqtt
      name: "Kids Bedroom Humidity"
      object_id: humidity
      state_topic: "usensor/humidity/getvalue"
      unit_of_measurement: "%"
      device_class: humidity
      state_class: measurement
    - platform: mqtt
      name: "Kids Bedroom illuminance"
      object_id: illuminance
      state_topic: "usensor/illuminance/getvalue"
      unit_of_measurement: "lx"
      device_class: illuminance
      state_class: measurement
    - platform: mqtt
      name: "Kids Bedroom UV"
      object_id: uv
      state_topic: "usensor/uv/getvalue"
      state_class: measurement
  binary_sensor:
    - platform: mqtt
      name: "Kids Bedroom Motion"
      state_topic: "usensor/motion/getvalue"
      device_class: motion
  light:
    - platform: mqtt
      name: "Kids Bedroom Light"
      object_id: kids_bedroom
      state_topic: "udimmer/channel2/getstate"
      command_topic: "udimmer/channel2/setstate"
      brightness_state_topic: "udimmer/channel2/getbrightness"
      brightness_command_topic: "udimmer/channel2/setbrightness"
      brightness_scale: 100
      retain: true
