kids_bedroom_sensor_climate:
  sensor:
    - platform: template
      sensors:
        kids_bedroom_sensor_climate_dew_point:
          friendly_name: "Kids Bedroom Sensor Climate Dew Point: "
          device_class: temperature
          unit_of_measurement: "째C"
          value_template: >-
            {% set temp = states('sensor.snzb_02_03_01_temperature') | float(0) %}
            {% set humidity = states('sensor.snzb_02_03_01_humidity') | float(0) %}
            {% set a0 = 373.15 / (273.15 + temp) %}
            {% set sum = -7.90298 * (a0 - 1) %}
            {% set sum = sum + 5.02808 * log(a0, 10) %}
            {% set sum = sum + -1.3816e-7 * (10 ** (11.344 * (1 - 1 / a0)) - 1) %}
            {% set sum = sum + 8.1328e-3 * (10 ** (-3.49149 * (a0 - 1)) - 1) %}
            {% set sum = sum + log(1013.246, 10) %}
            {% set vp = (10 ** (sum - 3)) * humidity %}
            {% set td = log(vp / 0.61078) %}
            {% set td = (241.88 * td) / (17.558 - td) %}
            {{ td | round(2) }}
        kids_bedroom_sensor_climate_heat_index:
          friendly_name: "Kids Bedroom Sensor Climate Heat Index: "
          device_class: temperature
          unit_of_measurement: "째C"
          value_template: >-
            {% set temp = states('sensor.snzb_02_03_01_temperature') | float(0) %}
            {% set humidity = states('sensor.snzb_02_03_01_humidity') | float(0) %}
            {% set t = temp * 9/5 + 32 %}
            {% set rh = humidity %}
            {% set hi = 0 %}
            {% if t <= 40.0 %}
              {% set hi = t %}
            {% else %}
              {% set hi = (-42.379 + 2.04901523*t + 10.14333127*rh - 0.22475541*t*rh - 0.00683783*t*t - 0.05481717*rh*rh + 0.00122874*t*t*rh + 0.00085282*t*rh*rh - 0.00000199*t*t*rh*rh) %}
              {% if rh < 13 and t >= 80 and t <= 112 %}
                {% set adjust = ((13 - rh) / 4)  * sqrt(17 - abs(t - 95) / 17) %}
                {% set hi = hi - adjust %}
              {% elif rh > 85 and t >= 80 and t <= 87 %}
                {% set adjust = ((rh - 85) / 10) * ((87 - t) / 5) %}
                {% set hi = hi + adjust %}
              {% elif t < 80 %}
                {% set hi = 0.5 * (t + 61.0 + ((t - 68.0) * 1.2) + (rh * 0.094)) %}
              {% endif %}
            {% endif %}
            {% set apparent_temp = (hi - 32) * 5/9 %}
            {{ apparent_temp | round(2) }}
        kids_bedroom_sensor_climate_humidex:
          friendly_name: "Kids Bedroom Sensor Climate Humidex: "
          device_class: temperature
          unit_of_measurement: "째C"
          value_template: >-
            {% set temp = states('sensor.snzb_02_03_01_temperature') | float(0) %}
            {% set dewpoint = states('sensor.kids_bedroom_sensor_climate_dew_point') | float(0) %}
            {% set ev = 6.11 * e**(5417.7530 * ((1 / 273.16) - (1 / (dewpoint + 273.15)))) %}
            {% set hv = (0.5555) * (ev - 10.0) %}
            {{ (temp + hv) | round(2) }}
        kids_bedroom_sensor_climate_humidex_perception:
          friendly_name: "Kids Bedroom Sensor Climate Humidex Perception: "
          value_template: >-
            {% set humidex = states('sensor.kids_bedroom_sensor_climate_humidex') | float(0) %}
            {% if humidex > 54 %}
              HEAT_STROKE
            {% elif humidex >= 45 %}
              DANGEROUS_DISCOMFORT
            {% elif humidex >= 40 %}
              GREAT_DISCOMFORT
            {% elif humidex >= 35 %}
              EVIDENT_DISCOMFORT
            {% elif humidex >= 30 %}
              NOTICABLE_DISCOMFORT
            {% else %}
              COMFORTABLE
            {% endif %}
        kids_bedroom_sensor_climate_thermal_perception:
          friendly_name: "Kids Bedroom Sensor Climate Thermal Perception: "
          value_template: >-
            {% set dewpoint = states('sensor.kids_bedroom_sensor_climate_dew_point') | float(0) %}
            {% if dewpoint < 10 %}
              DRY
            {% elif dewpoint < 13 %}
              VERY_COMFORTABLE
            {% elif dewpoint < 16 %}
              COMFORTABLE
            {% elif dewpoint < 18 %}
              OK_BUT_HUMID
            {% elif dewpoint < 21 %}
              SOMEWHAT_UNCOMFORTABLE
            {% elif dewpoint < 24 %}
              QUITE_UNCOMFORTABLE
            {% elif dewpoint < 26 %}
              EXTREMELY_UNCOMFORTABLE
            {% else %}
              SEVERELY_HIGH
            {% endif %}
        kids_bedroom_sensor_climate_absolute_humidity:
          friendly_name: "Kids Bedroom Sensor Climate Absolute Humidity: "
          device_class: humidity
          unit_of_measurement: "g/m3"
          value_template: >-
            {% set temp = states('sensor.snzb_02_03_01_temperature') | float(0) %}
            {% set humidity = states('sensor.snzb_02_03_01_humidity') | float(0) %}
            {% set abs_temperature = temp + 273.15 %}
            {% set abs_humidity = 6.112 %}
            {% set abs_humidity = abs_humidity * (e**((17.67 * temp) / (243.5 + temp))) %}
            {% set abs_humidity = abs_humidity * humidity %}
            {% set abs_humidity = abs_humidity * 2.1674 %}
            {% set abs_humidity = abs_humidity / abs_temperature %}
            {{ abs_humidity | round(2) }}
        kids_bedroom_sensor_climate_frost_point:
          friendly_name: "Kids Bedroom Sensor Climate Frost Point: "
          device_class: temperature
          unit_of_measurement: "째C"
          value_template: >-
            {% set temp = states('sensor.snzb_02_03_01_temperature') | float(0) %}
            {% set dewpoint = states('sensor.balcony_sensor_climate_dew_point') | float(0) %}
            {% set T = temp + 273.15 %}
            {% set Td = dewpoint + 273.15 %}
            {{ ((Td + (2671.02 / ((2954.61 / T) + 2.193665 * log(T) - 13.3448)) - T) - 273.15) | round(2) }}
        kids_bedroom_sensor_climate_frost_risk:
          friendly_name: "Kids Bedroom Sensor Climate Frost Risk: "
          value_template: >-
            {% set temp = states('sensor.snzb_02_03_01_temperature') | float(0) %}
            {% set thresholdAbsHumidity = 2.8 %}
            {% set absolutehumidity = states('sensor.kids_bedroom_sensor_climate_absolute_humidity') | float(0) %}
            {% set frostpoint = states('sensor.kids_bedroom_sensor_climate_frost_point') | float(0) %}
            {% if temp <= 1 and frostpoint <= 0 %}
              {% if absolutehumidity <= thresholdAbsHumidity %}
                LOW
              {% else %}
                HIGH
              {% endif %}
            {% elif temp <= 4 and frostpoint <= 0.5 and absolutehumidity > thresholdAbsHumidity %}
              MEDIUM
            {% else %}
              NONE
            {% endif %}
