kids_bedroom_sensor:
  sensor:
    - platform: history_stats
      name: kids_bedroom_sensor_light_on_duration_daily
      entity_id: light.kids_bedroom
      state: "on"
      type: time
      start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
      end: "{{ now() }}"
    - platform: history_stats
      name: kids_bedroom_sensor_light_on_duration_monthly
      entity_id: light.kids_bedroom
      state: "on"
      type: time
      start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"
      end: "{{ now() }}"
    - platform: template
      sensors:
        kids_bedroom_sensor_energy_light_daily:
          friendly_name: "Kids Bedroom Sensor Energy Light Daily: "
          value_template: "{{ states('sensor.kids_bedroom_sensor_light_on_duration_daily') | float * 6 * 8 * 0.001 | round(6) }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        kids_bedroom_sensor_energy_light_monthly:
          friendly_name: "Kids Bedroom Sensor Energy Light Monthly: "
          value_template: "{{ states('sensor.kids_bedroom_sensor_light_on_duration_monthly') | float * 6 * 8 * 0.001 | round(6) }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        kids_bedroom_sensor_energy_socket_daily:
          friendly_name: "Kids Bedroom Sensor Energy Socket Daily: "
          value_template: "{{ 0 }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
        kids_bedroom_sensor_energy_socket_monthly:
          friendly_name: "Kids Bedroom Sensor Energy Socket Monthly: "
          value_template: "{{ 0 }}"
          device_class: energy
          unit_of_measurement: kWh
          icon_template: mdi:counter
