mqtt:

  mqtt:
    discovery_prefix: homeassistant

  sensor:
    - platform: mqtt
      name: "Kids Bedroom Temperature"
      object_id: temperature
      state_topic: "usensor/temperature/getvalue"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement

    - platform: mqtt
      name: "Kids Bedroom Humidity"
      object_id: humidity
      state_topic: "usensor/humidity/getvalue"
      unit_of_measurement: "%"
      device_class: humidity
      state_class: measurement

    - platform: mqtt
      name: "Kids Bedroom illuminance"
      object_id: illuminance
      state_topic: "usensor/illuminance/getvalue"
      unit_of_measurement: "lx"
      device_class: illuminance
      state_class: measurement

    - platform: mqtt
      name: "Kids Bedroom UV"
      object_id: uv
      state_topic: "usensor/uv/getvalue"
      state_class: measurement

    - platform: mqtt
      name: "Mains Frequency"
      object_id: frequency
      state_topic: "udimmer/system/getfrequency"
      unit_of_measurement: "Hz"
      device_class: frequency
      state_class: measurement

  binary_sensor:
    - platform: mqtt
      name: "Kids Bedroom Motion"
      state_topic: "usensor/motion/getvalue"
      device_class: motion

  light:
    - platform: mqtt
      name: "Kitchen Light"
      object_id: kitchen
      state_topic: "udimmer/channel1/getstate"
      command_topic: "udimmer/channel1/setstate"
      brightness_state_topic: "udimmer/channel1/getbrightness"
      brightness_command_topic: "udimmer/channel1/setbrightness"
      brightness_scale: 100
      retain: true

    - platform: mqtt
      name: "Kids Bedroom Light"
      object_id: kids_bedroom
      state_topic: "udimmer/channel2/getstate"
      command_topic: "udimmer/channel2/setstate"
      brightness_state_topic: "udimmer/channel2/getbrightness"
      brightness_command_topic: "udimmer/channel2/setbrightness"
      brightness_scale: 100
      retain: true

    - platform: mqtt
      name: "Parents Bedroom Light"
      object_id: parents_bedroom
      state_topic: "udimmer/channel3/getstate"
      command_topic: "udimmer/channel3/setstate"
      brightness_state_topic: "udimmer/channel3/getbrightness"
      brightness_command_topic: "udimmer/channel3/setbrightness"
      brightness_scale: 100
      retain: true

    - platform: mqtt
      name: "Hallway Light"
      object_id: hallway
      state_topic: "udimmer/channel4/getstate"
      command_topic: "udimmer/channel4/setstate"
      brightness_state_topic: "udimmer/channel4/getbrightness"
      brightness_command_topic: "udimmer/channel4/setbrightness"
      brightness_scale: 100
      retain: true

    - platform: mqtt
      name: "Balcony Light"
      object_id: balcony
      state_topic: "udimmer/channel5/getstate"
      command_topic: "udimmer/channel5/setstate"
      brightness_state_topic: "udimmer/channel5/getbrightness"
      brightness_command_topic: "udimmer/channel5/setbrightness"
      brightness_scale: 100
      retain: true
