speaker:

  media_player:
    - platform: cmus
      name: cmus
      host: localhost
    - platform: mpd
      name: mpd
      host: localhost
      
  automation:
    - id: Test_Speaker_Automation
      alias: Test Speaker Automation
      trigger:
        - platform: state
          entity_id: binary_sensor.children_bedroom_motion
          from: "off"
          to: "on"
      action:
        - service: tts.google_translate_say
          entity_id: media_player.cmus
          data:
            message: Motion Detected!
