speaker:

  tts:
    - platform: google_translate

  media_player:
    - platform: cmus
      host: localhost
      password: password
      
  automation:
    - id: Test_Speaker_Automation
      alias: Test Speaker Automation
      trigger:
        - platform: state
          entity_id: binary_sensor.children_bedroom_motion
          from: "off"
          to: "on"
#       action:
#         - service: tts.google_translate_say
#           data:
#             entity_id: media_player.cmus
#             message: "Motion detected!"
