speaker:

  tts:
    - platform: google_translate

  media_player:
    - platform: cmus
      host: localhost
      password: password
      
  automation:
    - id: speaker_motion_detection
      alias: Speaker - Motion detection
      trigger:
        - platform: state
          entity_id: binary_sensor.children_bedroom_motion
          from: "off"
          to: "on"
      action:
        - service: tts.google_translate_say
          entity_id: media_player.cmus
          data:
            cache: false
            message: "Привет незнакомец! Я тебя сфотографировала и передала снимок в полицию."
            language: "ru"


    - id: speaker_temperature_balcony
      alias: Speaker - Temperature balcony
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/speaker/temperature/balcony"
      action:
        - service: tts.google_translate_say
          entity_id: media_player.cmus
          data:
            cache: false
            message: "Температура на улице {{states('sensor.temperature_balcony')}} градусов."
            language: "ru"
            
