telegram:

  telegram_bot:
    - platform: polling
      api_key: !secret telegram_api_key
      allowed_chat_ids:
        - !secret telegram_user_oleksandr

  notify:
    - name: telegram_user_oleksandr
      platform: telegram
      chat_id: !secret telegram_user_oleksandr

  automation:
    - id: System startup report
      alias: start_message
      initial_state: true
      trigger:
        - platform: homeassistant
          event: start
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: |
              {{ "\U0001F567" }} System startup at {{ states('sensor.time_date') }}

    - id: Ondemand system report
      alias: send_report_system
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: '/report_system'
      action:
        - service: script.turn_on
          entity_id: script.report_system

    - id: Ondemand light report
      alias: send_report_light
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: '/report_light'
      action:
        - service: script.turn_on
          entity_id: script.report_light

    - id: Ondemand sensor report
      alias: send_report_sensor
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: '/report_sensor'
      action:
        - service: script.turn_on
          entity_id: script.report_sensor

    - id: Turn off all lights
      alias: turn_off_all_lights
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: '/light_all_off'
        - platform: event
          event_type: telegram_command
          event_data:
            command: '/i_leave'
        - platform: event
          event_type: telegram_command
          event_data:
            command: '/i_sleep'
      action:
        - service: script.turn_on
          entity_id: script.all_lights_off
        - service: notify.telegram_user_oleksandr
          data:
            message: "All lights are off"

    - id: Telegeram start keyboard
      alias: telegram_start_keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/start"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Start message"
            data:
              keyboard:
                - "/report, /light, /climate"

    - id: Telegeram report keyboard
      alias: telegram_report_keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/report"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "All Reports"
            data:
              keyboard:
                - "/report_system, /report_light, /report_sensor"
                - "/start"

    - id: Telegeram light keyboard
      alias: telegram_light_keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/light"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "All Lights"
            data:
              keyboard:
                - "/light_hallway, /light_kitchen"
                - "/light_children_bedroom, /light_parents_bedroom"
                - "/light_balcony"
                - "/start"

    - id: Telegeram light-kitchen keyboard
      alias: telegram_light_kitchen_keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/light_kitchen"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Kitchen Light is {{ states('light.kitchen') }}"
            data:
              keyboard:
                - "/light_kitchen_on, /light_kitchen_off"
                - "/light_kitchen_switch, /light_kitchen_status"
                - "/light"

    - id: Telegeram light-kitchen-on keyboard
      alias: telegram_light_kitchen_on_keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/light_kitchen_on"
      action:
        - service: light.turn_on
          entity_id: light.kitchen

    - id: Telegeram light-kitchen-off keyboard
      alias: telegram_light_kitchen_off_keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/light_kitchen_off"
      action:
        - service: light.turn_off
          entity_id: light.kitchen

    - id: Telegeram light-kitchen-switch keyboard
      alias: telegram_light_kitchen_switch_keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/light_kitchen_switch"
      action:
        - service: light.turn_switch
          entity_id: light.kitchen

    - id: Telegeram light-kitchen-status keyboard
      alias: telegram_light_kitchen_status_keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/light_kitchen_status"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Kitchen Light is {{ states('light.kitchen') }}"

    - id: telegeram_climate_keyboard
      alias: Telegeram - Climate keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/climate"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "All Climates"
            data:
              keyboard:
                - "/climate_hallway, /climate_kitchen"
                - "/climate_children_bedroom, /climate_parents_bedroom"
                - "/climate_balcony"
                - "/start"

    - id: telegeram_climate_balcony_keyboard
      alias: Telegeram - Climate balcony keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/climate_balcony"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Balcony climate"
            data:
              keyboard:
                - "/climate_balcony_report, /climate_balcony_speaker"
                - "/climate"

    - id: telegram_climate_balcony_report
      alias: Telegram - Climate balcony report
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/climate_balcony_report"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Сейчас на улице температура {{ states('sensor.temperature_balcony') }} градусов и влажность {{ states('sensor.humidity_balcony') }} процентов."

    - id: telegram_climate_balcony_speaker
      alias: Telegram - Climate balcony speaker
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/climate_balcony_speaker"
      action:
        - service: tts.google_translate_say
          entity_id: media_player.cmus
          data:
            cache: false
            message: "Сейчас на улице температура {{ states('sensor.temperature_balcony') }} градусов и влажность {{ states('sensor.humidity_balcony') }} процентов."

    - id: telegeram_climate_children_bedroom_keyboard
      alias: Telegeram - Climate children bedroom keyboard
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/climate_children_bedroom"
      action:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Children bedroom climate"
            data:
              keyboard:
                - "/climate_children_bedroom_report, /climate_children_bedroom_speaker"
                - "/climate"
            
    - id: telegram_climate_children_bedroom_speaker
      alias: Telegram - Climate children bedroom speaker
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: "/climate_children_bedroom_speaker"
      action:
        - service: tts.google_translate_say
          entity_id: media_player.cmus
          data:
            cache: false
            message: "Сейчас в комнате температура {{ states('sensor.temperature') }} градусов и влажность {{ states('sensor.humidity') }} процентов."

  script:
    report_system:
      alias: Report of system state
      sequence:
        - service: notify.telegram_user_oleksandr
          data:
            message: |
              {{ "\U0001F4AC" }} System State
              {{ "\U0001F4A1" }} Lights: {{ states('sensor.all_lights') }} / {{ states('sensor.unavailable_lights') }}
              {{ "\U0001F50C" }} Switches: {{ states('sensor.all_switches') }} / {{ states('sensor.unavailable_switches') }}
              {{ "\U0001F321" }} Sensors: {{ states('sensor.all_sensors') }} / {{ states('sensor.unavailable_sensors') }}
              {{ "\U0001F51F" }} Binary Sensors: {{ states('sensor.all_binary_sensors') }} / {{ states('sensor.unavailable_binary_sensors') }}

    report_light:
      alias: Report of light state
      sequence:
        - service: notify.telegram_user_oleksandr
          data:
            message: |
              {{ "\U0001F4AC" }} Light State
              {{ "\U0001F4A1" }} Hallway is {{ states('light.hallway') }}
              {{ "\U0001F4A1" }} Kitchen is {{ states('light.kitchen') }}
              {{ "\U0001F4A1" }} Children Bedroom is {{ states('light.children_bedroom') }}
              {{ "\U0001F4A1" }} Parents Bedroom is {{ states('light.parents_bedroom') }}
              {{ "\U0001F4A1" }} Balcony is {{ states('light.balcony') }}

    report_sensor:
      alias: Report of sensor state
      sequence:
        - service: notify.telegram_user_oleksandr
          data:
            message: |
              {{ "\U0001F4AC" }} Sensor State
              {{ "\U0001F321" }} Mains Frequency is {{ states('sensor.frequency') }}
              {{ "\U0001F321" }} Temperature is {{ states('sensor.temperature') }}
              {{ "\U0001F321" }} Humidity is {{ states('sensor.humidity') }}

    send_message_1:
      alias: Send via notification service
      sequence:
        - service: notify.telegram_user_oleksandr
          data:
            message: "Current time - {{ states('sensor.time') }}. All right."

    send_message_motion_detected:
      alias: Motion detection notifier
      sequence:
        - service: camera.snapshot
          data:
            filename: /webcam_live_snapshot.jpg
          target:
            entity_id: camera.webcam_live
        - service: notify.telegram_user_oleksandr
          data:
            message: "Motion Detected!"
            photo:
              - file: /webcam_live_snapshot.jpg
                caption: Movement
