telegram_command_menu:

  automation:

    - id: Telegram - Command Menu Start Call
      alias: telegram_command_menu_start_call
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_command
          event_data:
            command: '/start'
      action:
        - service: telegram_bot.send_message
          data:
            target: "{{ trigger.event.data.user_id }}"
            message: |
              {{ '\U0001F527' }} Choose a room for control:
            inline_keyboard:
              - "{{ '\U0001F6B6' }} Hall:/hall_control, {{ '\U0001F374' }} Kitchen:/kitchen_control"
              - "{{ '\U0001F6B9' }} Kid's room:/kroom_control, {{ '\U0001F6C0' }} Bathroom:/bathroom_control"
              - "{{ '\U0001F3E2' }} Parent's room:/proom_control, {{ '\U0001F6B9' }} Balcony:/balcony_control"
              - "{{ '\U0001F6AB' }} Close:/close"

    - id: Telegram - Command Menu Start Control
      alias: telegram_command_menu_start_control
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_callback
          event_data: {}
      action:
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/close' }}"
            sequence:
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/back' }}"
            sequence:
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.user_id }}"
                  message: |
                    {{ '\U0001F527' }} Choose a room for control:
                  inline_keyboard:
                    - "{{ '\U0001F6B6' }} Hall:/hall_control, {{ '\U0001F374' }} Kitchen:/kitchen_control"
                    - "{{ '\U0001F6B9' }} Kid's room:/kroom_control, {{ '\U0001F6C0' }} Bathroom:/bathroom_control"
                    - "{{ '\U0001F3E2' }} Parent's room:/proom_control, {{ '\U0001F6B9' }} Balcony:/balcony_control"
                    - "{{ '\U0001F6AB' }} Close:/close"
