telegram_command_menu_hall:

  automation:
  
    - id: Telegram - Command Menu Hall Control
      alias: telegram_command_menu_hall_control
      initial_state: true
      trigger:
        - platform: event
          event_type: telegram_callback
          event_data: {}
      action:
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/hall_control' }}"
            sequence:
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message: &msg_hall |
                    Temperature - {{ states('sensor.temperature_hall') }}, Humidity - {{ states('sensor.humidity_hall') }}
                  inline_keyboard: &kbd_hall
                    - "{{ '\U0001F4A1' }} Domofon Sound - {% if is_state('switch.domofon_sound', 'on') %}🟢{% else %}🔴{% endif %}:/hall_domofon_sound_toggle"
                    - "{{ '\U0001F4A1' }} Light - {% if is_state('light.hall', 'on') %}🟢{% else %}🔴{% endif %}:/hall_light_toggle"
                    - "{{ '\U000021A9' }} Back:/back, {{ '\U000021AA' }} Update:/hall_control"
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/hall_domofon_sound_toggle' }}"
            sequence:
              - service: switch.toggle
                entity_id: switch.domofon_sound
              - delay:
                  milliseconds: 500
              - service: telegram_bot.answer_callback_query
                data:
                  callback_query_id: "{{ trigger.event.data.id }}"
                  message: |
                    {{ '\U0001F4AC' }} Domofon Sound is {% if is_state('switch.domofon_sound', 'on') %}on{% else %}off{% endif %}
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message: *msg_hall
                  inline_keyboard: *kbd_hall
          - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.command == '/hall_light_toggle' }}"
            sequence:
              - service: light.toggle
                entity_id: light.hall
              - delay:
                  milliseconds: 500
              - service: telegram_bot.answer_callback_query
                data:
                  callback_query_id: "{{ trigger.event.data.id }}"
                  message: |
                    {{ '\U0001F4AC' }} Light is {% if is_state('light.hall', 'on') %}on{% else %}off{% endif %}
              - service: telegram_bot.delete_message
                data_template:
                  chat_id: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id }}"
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message: *msg_hall
                  inline_keyboard: *kbd_hall
